### ISSUE TITLE
Change Site Region Field 'Name' to Dropdown

### ISSUE THREAD

**Issue by yucabeltran** [radical-doubting/anikultura-backend#136]
### **Describe the solution you'd like**

Change the 'name' and 'short name' field into a dropdown since there are only 17 regions in the Philippines.
Drop Database Column 'short_name' from table 'regions'.

### **Describe alternatives you've considered**

String input from users is considered but prone to a lot of validation errors.

### **Is your feature request related to a problem? Please describe.**

String input from users are prone to error.

**Comment by yucabeltran** [comment]
Check ChangeRegionNameToDropdown branch at https://github.com/radical-doubting/anikultura-backend/tree/ChangeRegionNameToDropdown where I implemented
1. Orchid Listener
2. Apply Scope

Issues Found:
1. Solution worked but the dropdown field refreshes once item is selected.
2. When listening to a specific field, public $target only accepts field in 'fieldname' format, but not 'fieldname.fieldid' format.

**Comment by jg-rivera** [comment]
The `short_name` field in the `regions` table is used for tags metrics because they are shorter and easier to read. They should not be removed.

A proposed simple fix is to focus on municipality and city edit/create screen instead. Do not allow the user to pick a region separately for a municipality and city. The region value should be derived from the province dropdown instead. For example, this will prevent a city from Bulacan province belonging to Mindanao region.
