### ISSUE TITLE
Visual Bug of a check mark even if there are invalid inputs in the farmland name

### ISSUE THREAD

**Issue by gpassport** [radical-doubting/anikultura-backend#176]
### Description

After an invalid input in the Farmland Management Page, a visual bug is marked as a check. This happens if do not input any information about the size of the farmland and proceed to save.

Overall the system still denies the invalid input for submission and this is just a  minor visual bug.

![image](https://user-images.githubusercontent.com/52141568/195761488-ec79fd6d-bc8c-4f04-967b-887020a14e80.png)

### Reproduction steps

1. Go to Farmland Management page: https://qa-anikultura-md.herokuapp.com/admin/enroll/farmer/
2. Click Add
3. Input an invalid farmland name, for example: "*&(*@(!"
4. Input other fields except for Size (ha), ensure that it is left blank
5. Click Save

### Expected behavior

Will not display a check mark for an invalid input in the farmland name.

**Comment by jg-rivera** [comment]
I managed to reproduce the bug. It is a possible bug with Orchid's client-side validation. Client-side validation might need to be disabled. Needs further investigation.

**Comment by jg-rivera** [comment]
I managed to fix a bug with the hectares input of the farmland edit screen. The reported visual bug cannot be solved at the moment since it is caused by the client-side validation library. The checkmark is caused by the `required` criteria being met in the client-side. This is indeed a cause of confusion. However, we still need to wait for a feature that allows us to set custom validation rules in the client-side so that the server-side validation rules are in sync.
